[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# SPA路由支持
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API代理（如果需要）
[[redirects]]
  from = "/api/*"
  to = "https://aistudio.alibaba-inc.com/api/:splat"
  status = 200
  headers = { X-From = "Netlify" }

# 安全头设置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[dev]
  command = "npm run dev"
  port = 3000
